/**
 * Transit Analysis API endpoint.
 *
 * Serves the cached AI-generated transit analysis from Redis.
 * Analysis is generated by the transit-analyzer module on each
 * metrics-collector flush cycle (every 5 minutes).
 *
 * GET /api/transit-analysis
 */
import type { IncomingMessage, ServerResponse } from 'node:http';
import { getCache } from '../lib/redis.js';
import { CACHE_KEYS } from '../lib/cache.js';
import { createLogger } from '../lib/logger.js';

const log = createLogger('api:analysis');

function sendJson(
  res: ServerResponse,
  status: number,
  body: Record<string, unknown>,
): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

export async function handleTransitAnalysis(
  _req: IncomingMessage,
  res: ServerResponse,
): Promise<void> {
  try {
    const cached = await getCache<{
      analysis: string;
      generatedAt: string;
      model: string;
    }>(CACHE_KEYS.transitAnalysis);

    if (cached) {
      sendJson(res, 200, cached);
      return;
    }

    sendJson(res, 202, {
      analysis: 'Transit analysis is being generated. Check back in a few minutes.',
      generatedAt: new Date().toISOString(),
      model: 'pending',
    });
  } catch (err) {
    log.error({ err: err instanceof Error ? err.message : err }, 'request error');
    sendJson(res, 500, {
      error: 'Internal server error',
    });
  }
}
